#
# Challonge config
#


# HOW TO SETUP
# go to https://twitchapps.com/tmi/ and connect with Twitch
# put the ouath:xxxx key under oauth down below
# put the accounts username under username
# put your twitch channel under channel
# done


# CHAT BOT
# You can use your own Twitch account if you don't have a dedicated bot.

# Bot OAuth (grab at https://twitchapps.com/tmi/)
oauth: 'oauth:xxxx'

# Bot username
username: 'examplename'

# Twitch channel
channel: 'examplechannel'

# GENERAL SETTINGS

# Vote delay (amount of time between vote end and next vote) in seconds
delay: 60

# Vote time (amount of time viewers have to vote) in seconds
time: 15

# Hide commands from ingame (commands will be sent in twitch chat)
hide: false

# ADVANCED SETTINGS

# Vote actions (actions users can choose between)
# you can add more actions if you want to.
# name: showed to chat
# action: command executed
actions: '{ "arr": [
  { "name": "Kick players", "action": "kick @a Your fate has been decided by twitch chat" },
  { "name": "Give 10 Diamonds", "action": "give @a diamond 10" },
  { "name": "Give 10 Dirt", "action": "give @a dirt 10" },
  { "name": "Levitation", "action": "effect give @a levitation 15 1 true" },
  { "name": "Blindness", "action": "effect give @a blindness 30 1 true" },
  { "name": "Slowness", "action": "effect give @a minecraft:slowness 30 2 true" },
  { "name": "Give Diamond Hoe", "action": "give @a minecraft:diamond_hoe" },
  { "name": "Instant Damage", "action": "effect give @a minecraft:instant_damage" },
  { "name": "No jumping", "action": "effect give @a minecraft:jump_boost 30 150 true" },
  { "name": "Regen", "action": "effect give @a regeneration 5 10 true" },
  { "name": "Double Health", "action": "effect give @a minecraft:health_boost 30 4 true" },
  { "name": "Poison", "action": "effect give @a minecraft:poison 10 1 true" },
  { "name": "10 XP levels", "action": "xp add @a 10 levels" },
  { "name": "Speed V", "action": "effect give @a minecraft:speed 30 4 true" },
  { "name": "No block breaking", "action": "effect give @a minecraft:mining_fatigue 30 10 true" },
  { "name": "Nausea", "action": "effect give @a minecraft:nausea 30 1 true" },
  { "name": "Wallhack", "action": "effect give @e minecraft:glowing 30 1 true" },
  { "name": "Super Strong", "action": "effect give @a minecraft:strength 30 10 true" },
  { "name": "Give Bedrock", "action": "give @a minecraft:bedrock" },
  { "name": "Give 10 Iron Ingot", "action": "give @a minecraft:iron_ingot 10" },
  { "name": "Give 10 Gold Ingot", "action": "give @a minecraft:gold_ingot 10" },
  { "name": "Give 10 TNT", "action": "give @a tnt 10" },
  { "name": "Give Beacon", "action": "give @a minecraft:beacon" },
  { "name": "Give Anvil", "action": "give @a minecraft:anvil" },
  { "name": "Falling Anvil", "action": "execute at @a run setblock ~ ~12 ~ anvil" },
  { "name": "Spawn Creeper", "action": "execute at @a run summon creeper" },
  { "name": "Spawn Boat", "action": "execute at @a run summon boat" },
  { "name": "Summon Lightning", "action": "execute at @a run summon minecraft:lightning_bolt" },
  { "name": "Apache Helicopter", "action": "execute at @a run summon bat ~ ~ ~ {Passengers:[{id:skeleton}]}" },
  { "name": "Set Night-Time", "action": "time set night" },
  { "name": "Set Day-Time", "action": "time set day" },
  { "name": "Spawn giant", "action": "execute at @a run summon giant" },
  { "name": "Creeper Sound", "action": "execute as @a run playsound minecraft:entity.creeper.primed player @a" },
  { "name": "Burn Player", "action": "execute at @a run setblock ~ ~ ~ fire" },
  { "name": "Force eat Chorus Fruit", "action": "give @a minecraft:chorus_fruit" },
  { "name": "Fall 5 blocks", "action": "execute at @a run fill ~-1 ~ ~-1 ~1 ~-5 ~1 air" },
  { "name": "Pumpkin on head", "action": "replaceitem entity @a armor.head minecraft:carved_pumpkin" },
  { "name": "Give 10 Steak", "action": "give @a minecraft:cooked_beef 10" },
  { "name": "Give 16 Egg", "action": "give @a minecraft:egg 16" }
]}'