#
# MineTwitch config
#


# HOW TO SETUP
# go to https://twitchapps.com/tmi/ and connect with Twitch
# put the ouath:xxxx key under oauth down below
# put the accounts username under username
# put your twitch channel under channel
# done


# CHAT BOT
# You can use your own Twitch account if you don't have a dedicated bot.

# Bot OAuth (grab at https://twitchapps.com/tmi/)
oauth: 'oauth:xxxx'

# Bot username
username: 'examplename'

# Twitch channel
channel: 'examplechannel'

# GENERAL SETTINGS

# Vote delay (amount of time between vote end and next vote) in seconds
delay: 60

# Vote time (amount of time viewers have to vote) in seconds
time: 15

# Hide commands from ingame (commands will be sent in twitch chat)
hide: false