name: MineTwitch
version: @version@
main: com.github.risbun.minetwitch.Main
api-version: 1.16
commands:
  mt:
    description: MineTwitch
    usage: /mt
  mtreload:
    description: Reload config
    usage: /mtreload