name: MineTwitch
version: 1.0.1
main: se.laxmine.minetwitch.Main
api-version: 1.16
commands:
  mt:
    description: MineTwitch
    usage: /mt
  mtreload:
    description: Reload config
    usage: /mtreload